<br>
<p style="text-align: center;"><font size=6><b>EAE1106 - Métodos Computacionais para Economistas</b></font></p>

<p style="text-align: center;"> Departamento de Economia | Faculdade de Economia, Administração, Contabilidade e Atuaria <br> Universidade de São Paulo <br><br></p>
    
<p style="text-align: center;"><font size=4>Prof. Danilo Souza e Prof. Claudio Lucinda</font> <br>
    <a href="https://www.danilosouza.com/teaching/eae1106">danilosouza.com/teaching/eae1106</a> | <a href="https://github.com/claudiolucinda/EAE1106">github.com/claudiolucinda/EAE1106</a>
    <br><br>
</p>


<p style="text-align: center;">2º semestre de 2022</p>
<hr>

<font size=6><b>Aula 10 e Aula 11 </b></font>
<br><br>

Ao longo das próximas duas aulas discutiremos uma das bibliotecas mais importantes de toda essa nossa jornada de introdução ao Python: **Pandas**.

<h1>Plano de aula<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#O-que-é-o-Pandas?" data-toc-modified-id="O-que-é-o-Pandas?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>O que é o Pandas?</a></span></li><li><span><a href="#Objetos-no-Pandas" data-toc-modified-id="Objetos-no-Pandas-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Objetos no Pandas</a></span></li><li><span><a href="#DataFrame--e-o-coração-do-Pandas" data-toc-modified-id="DataFrame--e-o-coração-do-Pandas-3"><span class="toc-item-num">3&nbsp;&nbsp;</span><em>DataFrame</em>  e o coração do Pandas</a></span><ul class="toc-item"><li><span><a href="#Características-básicas" data-toc-modified-id="Características-básicas-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Características básicas</a></span></li><li><span><a href="#Indexação,-seleção-e-filtragem" data-toc-modified-id="Indexação,-seleção-e-filtragem-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Indexação, seleção e filtragem</a></span></li><li><span><a href="#Operações-com-colunas-numéricas" data-toc-modified-id="Operações-com-colunas-numéricas-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Operações com colunas numéricas</a></span></li><li><span><a href="#Operações-com-colunas-contendo-strings" data-toc-modified-id="Operações-com-colunas-contendo-strings-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Operações com colunas contendo strings</a></span></li><li><span><a href="#Agrupamento-e-junção-de-DataFrames" data-toc-modified-id="Agrupamento-e-junção-de-DataFrames-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Agrupamento e junção de DataFrames</a></span></li><li><span><a href="#Eficiência-e-dtypes" data-toc-modified-id="Eficiência-e-dtypes-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Eficiência e <em>dtypes</em></a></span></li></ul></li><li><span><a href="#Exportando-o-DataFrame" data-toc-modified-id="Exportando-o-DataFrame-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Exportando o DataFrame</a></span></li></ul></div>

***

# O que é o Pandas?

Pandas é uma biblioteca que contém objetos específicos e ferramentas próprias a esses objetos que permitem realizar limpeza, organização e análise de dados de forma bastante eficiente no Python. Não à toa, é uma das bibliotecas mais utilizadas na linguagem hoje em dia, um pré-requisito para a maior parte das aplicações de ciência dos dados e aprendizado de máquina.

Embora o Pandas se utilize em grande medida da estrutura e lógica do NumPy e seus arrays, a biblioteca é projetada para trabalhar com dados tabulares e heterogêneos. Como já vimos, o NumPy é mais adequado para trabalhar com dados homogêneos e em sua maior parte numéricos.

São dois os objetos particulares ao Pandas: `Series` e `DataFrame`.

Você pode pensar em uma série como uma "coluna" de dados, como uma sequência de observações em uma única variável. Por outro lado, um DataFrame é um objeto bidimensional para armazenar colunas de dados relacionadas, assim como uma tabela, com linhas e colunas, no Microsoft Excel.

# Objetos no Pandas

Primeiro passo é importar o Pandas.

In [1]:
import pandas as pd

Uma vez importado, vamos começar criando duas listas: uma contendo o número de pessoas ocupadas (em mil pessoas) no Brasil de 2012 a 2021 e outra contendo exatamente o intervalo de anos. 

In [2]:
pessoas_ocupadas = [90593,92170,92962,92366,90174,92228,93534,95515,87225,95747]
anos = list(range(2012,2021+1))

print(pessoas_ocupadas)
print(anos)

[90593, 92170, 92962, 92366, 90174, 92228, 93534, 95515, 87225, 95747]
[2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]


Para criar uma série basta utilizar a função `pandas.Series`, que recebe como argumento os valores da série e os índices da série, que serão justamente os valores que identificam cada linha.

In [3]:
series_pessoas_ocup = pd.Series(data=pessoas_ocupadas,index=anos)

print(type(series_pessoas_ocup),'\n')
print(series_pessoas_ocup)

<class 'pandas.core.series.Series'> 

2012    90593
2013    92170
2014    92962
2015    92366
2016    90174
2017    92228
2018    93534
2019    95515
2020    87225
2021    95747
dtype: int64


Já para o caso de um DataFrame, podemos criá-lo através da função `pandas.DataFrame`. Essa função recebe os dados que irão compor as colunas de dados de diversas formas, mas umas das mais intuitivas é através da utilização de dicionários. Seguindo o exemplo anterior, vamos criar um DataFrame com as informações de pessoas ocupadas, desocupadas, dentro e fora da força de trabalho.

Primeiro passo é definir o dicionário com esses dados. 

In [4]:
dados = {
    'ocupadas': [90593,92170,92962,92366,90174,92228,93534,95515,87225,95747],
    'desocupadas': [6730,6151,6555,9222,12476,12453,12413,11903,14412,12011],
    'na forca': [97322,98321,99516,101588,102650,104682,105947,107418,101637,107758],
    'fora da forca': [58007,59244,60162,60092,60953,60777,61299,61579,69042,64525]
}

print(dados)

{'ocupadas': [90593, 92170, 92962, 92366, 90174, 92228, 93534, 95515, 87225, 95747], 'desocupadas': [6730, 6151, 6555, 9222, 12476, 12453, 12413, 11903, 14412, 12011], 'na forca': [97322, 98321, 99516, 101588, 102650, 104682, 105947, 107418, 101637, 107758], 'fora da forca': [58007, 59244, 60162, 60092, 60953, 60777, 61299, 61579, 69042, 64525]}


Agora basta definir o DataFrame usando como argumento esse dicionários `dados`.

In [5]:
dados_emprego = pd.DataFrame(data=dados,index=anos)

print(type(dados_emprego),'\n')
dados_emprego

<class 'pandas.core.frame.DataFrame'> 



ocupadas  desocupadas  na forca  fora da forca
2012     90593         6730     97322          58007
2013     92170         6151     98321          59244
2014     92962         6555     99516          60162
2015     92366         9222    101588          60092
2016     90174        12476    102650          60953
2017     92228        12453    104682          60777
2018     93534        12413    105947          61299
2019     95515        11903    107418          61579
2020     87225        14412    101637          69042
2021     95747        12011    107758          64525

# _DataFrame_  e o coração do Pandas

Agora que já apresentamos os dois tipos de objetos e como criá-los na mão, vamos avançar e trabalhar com dados trazidos de algum arquivo externo. É comum nos depararmos com arquivos do tipo `.csv` e é com ele que trabalharemos no Pandas, embora o Pandas seja flexível e nos permita trazer para dentro do Python arquivos de várias terminações como `.txt`, `.xlsx`, `.json`, `.dta`, etc.

A ideia daqui para frente é trabalhar com os dados do site [Our World in Data](https://ourworldindata.org/) sobre número de casos de covid-19, mortes e excesso de mortes atrelados à doença, e número de doses de vacina aplicadas ao redor do mundo desde o início da pandemia, em fevereiro de 2020. Esses dados são atualizados semanalmente e disponibilizados na plataforma Kaggle. O arquivo específico com o qual trabalharemos está disponível no Moodle e deve ser baixado para a sua máquina local.

Mas antes de aprendermos como trabalhar com um dataframe e as funcionalidades que o Pandas nos traz precisamos ler o arquivo com os nossos dados. Comecemos pela função `os.chdir` do pacote `os` para mudar o diretório base do Python para o diretório no qual o nosso arquivo se encontra:

In [6]:
import os

# Qual o diretório no qual o Python está trabalhando? A função getcwd() nos diz isso
print('Diretório inicial: {}'.format(os.getcwd()))

# Vamos mudar para o nosso diretório atual
os.chdir('D:/Dropbox/Projetos e trabalhos/FEAUSP/Cursos/EAE1106 - Metodos Computacionais para Economistas/Notebooks')
print('Diretório final: {}'.format(os.getcwd()))

Diretório inicial: C:\Users\Danilo
Diretório final: D:\Dropbox\Projetos e trabalhos\FEAUSP\Cursos\EAE1106 - Metodos Computacionais para Economistas\Notebooks


Quais são os arquivos disponíveis nesse diretório? A função `os.listdir()` lista as pastas e arquivos disponíveis no diretório que estamos trabalhando.

In [7]:
os.listdir()

['df_resultado_aula_pandas.csv',
 'EAE1106 - Aula01.html',
 'EAE1106 - Aula01.ipynb',
 'EAE1106 - Aula02.html',
 'EAE1106 - Aula02.ipynb',
 'EAE1106 - Aula03 e Aula04.html',
 'EAE1106 - Aula03 e Aula04.ipynb',
 'EAE1106 - Aula05.html',
 'EAE1106 - Aula05.ipynb',
 'EAE1106 - Aula06 e Aula07.html',
 'EAE1106 - Aula06 e Aula07.ipynb',
 'EAE1106 - Aula08.html',
 'EAE1106 - Aula08.ipynb',
 'EAE1106 - Aula09.html',
 'EAE1106 - Aula09.ipynb',
 'EAE1106 - Aula10.html',
 'EAE1106 - Exercícios.ipynb',
 'owid-covid-data_top10.csv']

Legal, Agora utilizaremos a função `pandas.read_csv` para ler o arquivo `owid-covid-data_top10.csv`. Esse arquivo contém as informações para os 10 países com o maior número reportado de casos de covid-19.

In [8]:
df_covid = pd.read_csv('owid-covid-data_top10.csv', sep=',', encoding='utf8')
type(df_covid)

pandas.core.frame.DataFrame

## Características básicas

Alguns métodos específicos ao objeto DataFrame nos são incrivelmente úteis quando queremos ter uma leitura rápida do que acabamos de gerar.

* `df.info()` nos retorna algumas informações técnicas do dataframe `df`, como o formato dos dados presentes em cada coluna.
* `df.head()` nos retorna as cinco primeiras linhas.
* `df.tail()` nos retorna as cinco últimas linhas.
* `df.describe()` nos retorna uma tabela de estatísticas descritivas das colunas numéricas.

Vejamos o que esses métodos nos retornam no nosso caso:

In [9]:
df_covid.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7663 entries, 0 to 7662
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   iso_code                                    7663 non-null   object 
 1   continent                                   7663 non-null   object 
 2   location                                    7663 non-null   object 
 3   date                                        7663 non-null   object 
 4   total_cases                                 7663 non-null   float64
 5   new_cases                                   7641 non-null   float64
 6   new_cases_smoothed                          7484 non-null   float64
 7   total_deaths                                7345 non-null   float64
 8   new_deaths                                  7327 non-null   float64
 9   new_deaths_smoothed                         7173 non-null   float64
 10  total_cases_

In [10]:
df_covid.head()

iso_code      continent location        date  total_cases  new_cases  \
0      BRA  South America   Brazil  2020-02-26          1.0        1.0   
1      BRA  South America   Brazil  2020-02-27          1.0        0.0   
2      BRA  South America   Brazil  2020-02-28          1.0        0.0   
3      BRA  South America   Brazil  2020-02-29          2.0        1.0   
4      BRA  South America   Brazil  2020-03-01          2.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...   
1                 NaN           NaN         NaN                  NaN  ...   
2                 NaN           NaN         NaN                  NaN  ...   
3                 NaN           NaN         NaN                  NaN  ...   
4                 NaN           NaN         NaN                  NaN  ...   

   female_smokers  male_smokers  handwashing_facilities  \
0            10.1          17.9                     NaN   
1            10.1          17.9                     NaN   
2            10.1          17.9                     NaN   
3            10.1          17.9                     NaN   
4            10.1          17.9                     NaN   

   hospital_beds_per_thousand  life_expectancy  human_development_index  \
0                         2.2            75.88                    0.765   
1                         2.2            75.88                    0.765   
2                         2.2            75.88                    0.765   
3                         2.2            75.88                    0.765   
4                         2.2            75.88                    0.765   

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN   
1                                   NaN                          NaN   
2                                   NaN                          NaN   
3                                7049.6                         3.31   
4                                   NaN                          NaN   

   excess_mortality  excess_mortality_cumulative_per_million  
0               NaN                                      NaN  
1               NaN                                      NaN  
2               NaN                                      NaN  
3              5.25                                32.943066  
4               NaN                                      NaN  

[5 rows x 67 columns]

Ué, mas não são 67 colunas? Onde estão todas elas?
Por padrão o pandas mostra apenas uma parcela do total, para alterar essas opções basta utilizar a função `pd.set_option` e mudar o argumento relacionado ao número máximo de colunas.

In [11]:
pd.set_option('display.max_columns', 100)
df_covid.head()

iso_code      continent location        date  total_cases  new_cases  \
0      BRA  South America   Brazil  2020-02-26          1.0        1.0   
1      BRA  South America   Brazil  2020-02-27          1.0        0.0   
2      BRA  South America   Brazil  2020-02-28          1.0        0.0   
3      BRA  South America   Brazil  2020-02-29          2.0        1.0   
4      BRA  South America   Brazil  2020-03-01          2.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
0                 NaN           NaN         NaN                  NaN   
1                 NaN           NaN         NaN                  NaN   
2                 NaN           NaN         NaN                  NaN   
3                 NaN           NaN         NaN                  NaN   
4                 NaN           NaN         NaN                  NaN   

   total_cases_per_million  new_cases_per_million  \
0                    0.005                  0.005   
1                    0.005                  0.000   
2                    0.005                  0.000   
3                    0.009                  0.005   
4                    0.009                  0.000   

   new_cases_smoothed_per_million  total_deaths_per_million  \
0                             NaN                       NaN   
1                             NaN                       NaN   
2                             NaN                       NaN   
3                             NaN                       NaN   
4                             NaN                       NaN   

   new_deaths_per_million  new_deaths_smoothed_per_million  reproduction_rate  \
0                     NaN                              NaN                NaN   
1                     NaN                              NaN                NaN   
2                     NaN                              NaN                NaN   
3                     NaN                              NaN                NaN   
4                     NaN                              NaN                NaN   

   icu_patients  icu_patients_per_million  hosp_patients  \
0           NaN                       NaN            NaN   
1           NaN                       NaN            NaN   
2           NaN                       NaN            NaN   
3           NaN                       NaN            NaN   
4           NaN                       NaN            NaN   

   hosp_patients_per_million  weekly_icu_admissions  \
0                        NaN                    NaN   
1                        NaN                    NaN   
2                        NaN                    NaN   
3                        NaN                    NaN   
4                        NaN                    NaN   

   weekly_icu_admissions_per_million  weekly_hosp_admissions  \
0                                NaN                     NaN   
1                                NaN                     NaN   
2                                NaN                     NaN   
3                                NaN                     NaN   
4                                NaN                     NaN   

   weekly_hosp_admissions_per_million  new_tests  total_tests  \
0                                 NaN        NaN          NaN   
1                                 NaN        NaN          NaN   
2                                 NaN        NaN          NaN   
3                                 NaN        NaN          NaN   
4                                 NaN        NaN          NaN   

   total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  \
0                       NaN                     NaN                 NaN   
1                       NaN                     NaN                 NaN   
2                       NaN                     NaN                 NaN   
3                       NaN                     NaN                 NaN   
4                       NaN                     NaN                 NaN   

   new_tests_smoothe

In [12]:
df_covid.tail()

iso_code      continent       location        date  total_cases  \
7658      USA  North America  United States  2022-03-01   79091361.0   
7659      USA  North America  United States  2022-03-02   79143716.0   
7660      USA  North America  United States  2022-03-03   79196008.0   
7661      USA  North America  United States  2022-03-04   79250509.0   
7662      USA  North America  United States  2022-03-05   79265726.0   

      new_cases  new_cases_smoothed  total_deaths  new_deaths  \
7658    47031.0           62331.429      952423.0      1691.0   
7659    52355.0           57824.857      954518.0      2095.0   
7660    52292.0           55673.857      956261.0      1743.0   
7661    54501.0           52764.286      958144.0      1883.0   
7662    15217.0           47989.857      958437.0       293.0   

      new_deaths_smoothed  total_cases_per_million  new_cases_per_million  \
7658             1830.000               237572.183                141.270   
7659             1725.000               237729.446                157.262   
7660             1553.714               237886.519                157.073   
7661             1497.857               238050.227                163.708   
7662             1425.714               238095.936                 45.708   

      new_cases_smoothed_per_million  total_deaths_per_million  \
7658                         187.229                  2860.859   
7659                         173.693                  2867.152   
7660                         167.231                  2872.387   
7661                         158.492                  2878.043   
7662                         144.150                  2878.923   

      new_deaths_per_million  new_deaths_smoothed_per_million  \
7658                   5.079                            5.497   
7659                   6.293                            5.182   
7660                   5.236                            4.667   
7661                   5.656                            4.499   
7662                   0.880                            4.283   

      reproduction_rate  icu_patients  icu_patients_per_million  \
7658               0.59        7314.0                    21.970   
7659               0.59        6993.0                    21.005   
7660                NaN        7015.0                    21.071   
7661                NaN        6203.0                    18.632   
7662                NaN           NaN                       NaN   

      hosp_patients  hosp_patients_per_million  weekly_icu_admissions  \
7658        36214.0                    108.778                    NaN   
7659        34699.0                    104.228                    NaN   
7660        34108.0                    102.453                    NaN   
7661        30560.0                     91.795                    NaN   
7662            NaN                        NaN                    NaN   

      weekly_icu_admissions_per_million  weekly_hosp_admissions  \
7658                                NaN                 32132.0   
7659                                NaN                 30821.0   
7660                                NaN                 29613.0   
7661                                NaN                 28778.0   
7662                                NaN                     NaN   

      weekly_hosp_admissions_per_million  new_tests  total_tests  \
7658                              96.517        NaN          NaN   
7659                              92.579        NaN          NaN   
7660                              88.951        NaN          NaN   
7661                              86.442        NaN          NaN   
7662                                 NaN        NaN          NaN   

      total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  \
7658                       NaN                     NaN                 NaN   
7659                       NaN                     NaN                 NaN   
7660                       NaN            

In [13]:
df_covid.describe()

total_cases     new_cases  new_cases_smoothed   total_deaths  \
count  7.663000e+03  7.641000e+03         7484.000000    7345.000000   
mean   7.413453e+06  3.248569e+04        32590.349244  143683.851464   
std    1.200763e+07  6.990790e+04        66130.926542  193260.956591   
min    1.000000e+00  0.000000e+00            0.000000       1.000000   
25%    2.297820e+05  1.333000e+03         1440.107250   10145.000000   
50%    2.702681e+06  9.921000e+03        11149.928500   83976.000000   
75%    7.906961e+06  3.357100e+04        35266.357250  149512.000000   
max    7.926573e+07  1.368167e+06       802518.429000  958437.000000   

        new_deaths  new_deaths_smoothed  total_cases_per_million  \
count  7327.000000          7173.000000              7663.000000   
mean    420.451071           423.776663             40129.002883   
std     656.855964           611.463015             53182.233431   
min       0.000000             0.000000                 0.001000   
25%      23.000000            27.857000              2831.535000   
50%     161.000000           177.714000             17491.567000   
75%     535.500000           567.143000             64999.770000   
max    4529.000000          4190.000000            342095.547000   

       new_cases_per_million  new_cases_smoothed_per_million  \
count            7641.000000                     7484.000000   
mean              218.335670                      215.706487   
std               514.898513                      475.288902   
min                 0.000000                        0.000000   
25%                12.022000                       12.578000   
50%                62.362000                       67.154500   
75%               209.744000                      216.940500   
max              7453.161000                     5436.723000   

       total_deaths_per_million  new_deaths_per_million  \
count               7345.000000             7327.000000   
mean                 849.127797                2.393236   
std                  856.364728                3.168872   
min                    0.001000                0.000000   
25%                   98.069000                0.214000   
50%                  554.520000                0.977000   
75%                 1631.352000                3.464500   
max                 3047.832000               26.683000   

       new_deaths_smoothed_per_million  reproduction_rate  icu_patients  \
count                      7173.000000         7292.00000   4278.000000   
mean                          2.408332            1.10120   3303.139551   
std                           2.914506            0.39357   5453.474130   
min                           0.000000            0.19000      8.000000   
25%                           0.242000            0.90000    348.000000   
50%                           1.106000            1.03000   1134.000000   
75%                           3.727000            1.22000   3489.750000   
max                          18.308000            6.14000  28891.000000   

       icu_patients_per_million  hosp_patients  hosp_patients_per_million  \
count               4278.000000    2861.000000                2861.000000   
mean                  24.102691   22806.165676                 194.417561   
std                   22.399457   26308.573419                 149.807859   
min                    0.156000     127.000000                   2.104000   
25%                    5.410000    6009.000000                  78.055000   
50%                   15.918000   14665.000000                 138.495000   
75%                   39.497000   28951.000000                 307.959000   
max                  104.105000  154536.000000                 637.877000   

       weekly_icu_admissions  weekly_icu_admissions_per_million  \
count            1377.000000                        1377.000000   
mean             1051.387073                          15.427283   
std               842.146810                          12.298781   

Uma outra coisa que pode ser bastante interessante é saber quantas vezes os valores de determinada variável se repetem. Quantas vezes cada país da base de dados aparece no DataFrame?

In [14]:
df_covid['location'].value_counts()

Japan             774
South Korea       774
United States     774
France            772
Germany           769
India             766
Italy             765
Russia            765
United Kingdom    765
Brazil            739
Name: location, dtype: int64

In [15]:
df_covid['location'].value_counts(normalize=True,dropna=False)

Japan             0.101005
South Korea       0.101005
United States     0.101005
France            0.100744
Germany           0.100352
India             0.099961
Italy             0.099830
Russia            0.099830
United Kingdom    0.099830
Brazil            0.096437
Name: location, dtype: float64

Por fim, podemos ordenar o DataFrame de acordo com uma coluna ou um conjunto de colunas.
Qual eram os países com o maior número de novos casos de covid reportados no dia 1 de março de 2022?

In [16]:
df_covid[df_covid['date']=='2022-03-01'].sort_values(by=['new_cases'], ascending=False)

iso_code      continent        location        date  total_cases  \
6119      KOR           Asia     South Korea  2022-03-01    3492686.0   
6884      GBR         Europe  United Kingdom  2022-03-01   19036570.0   
5345      RUS         Europe          Russia  2022-03-01   16257688.0   
1506      FRA         Europe          France  2022-03-01   22835320.0   
4580      JPN           Asia           Japan  2022-03-01    5071249.0   
2275      DEU         Europe         Germany  2022-03-01   14974722.0   
3806      ITA         Europe           Italy  2022-03-01   12829972.0   
7658      USA  North America   United States  2022-03-01   79091361.0   
734       BRA  South America          Brazil  2022-03-01   28818850.0   
3041      IND           Asia           India  2022-03-01   42938599.0   

      new_cases  new_cases_smoothed  total_deaths  new_deaths  \
6119   219237.0          166214.857        8266.0        96.0   
6884    99485.0           41712.714      161773.0       269.0   
5345    96092.0          118164.000      345427.0       772.0   
1506    79794.0           54468.000      138645.0       209.0   
4580    65368.0           65592.143       23905.0       238.0   
2275    62096.0          135435.286      123024.0        75.0   
3806    47136.0           39339.429      155000.0       233.0   
7658    47031.0           62331.429      952423.0      1691.0   
734     22279.0           65271.286      649922.0       246.0   
3041     7554.0           10224.000      514246.0       223.0   

      new_deaths_smoothed  total_cases_per_million  new_cases_per_million  \
6119               94.143                68076.668               4273.194   
6884              116.857               279099.479               1458.572   
5345              760.857               111421.169                658.561   
1506              185.714               338692.415               1183.501   
4580              223.714                40231.789                518.585   
2275              159.429               178481.978                740.115   
3806              212.571               212531.216                780.818   
7658             1830.000               237572.183                141.270   
734               598.143               134671.651                104.111   
3041              232.000                30815.502                  5.421   

      new_cases_smoothed_per_million  total_deaths_per_million  \
6119                        3239.728                   161.114   
6884                         611.560                  2371.791   
5345                         809.830                  2367.365   
1506                         807.867                  2056.376   
4580                         520.363                   189.646   
2275                        1614.237                  1466.309   
3806                         651.666                  2567.608   
7658                         187.229                  2860.859   
734                          305.015                  3037.112   
3041                           7.337                   369.056   

      new_deaths_per_million  new_deaths_smoothed_per_million  \
6119                   1.871                            1.835   
6884                   3.944                            1.713   
5345                   5.291                            5.214   
1506                   3.100                            2.755   
4580                   1.888                            1.775   
2275                   0.894                            1.900   
3806                   3.860                            3.521   
7658                   5.079                            5.497   
734                    1.150                            2.795   
3041                   0.160                            0.166   

      reproduction_rate  icu_patients  icu_patients_per_million  \
6119               1.34         727.0                    14.170   
6884               1.05         278.0                     4.

Note que no código acima utilizamos uma forma de filtragem dos dados com base em uma condição, que é a data ser igual a 01 de março de 2022. Vamos ir com calma e mostrar todos os passos para realizar indexação, seleção e filtragem em dataframes agora.

## Indexação, seleção e filtragem

Podemos selecionar um intervalo particular de linhas do DataFrame usando a lógica de indexação de sempre.

In [17]:
df_covid[0:5]

iso_code      continent location        date  total_cases  new_cases  \
0      BRA  South America   Brazil  2020-02-26          1.0        1.0   
1      BRA  South America   Brazil  2020-02-27          1.0        0.0   
2      BRA  South America   Brazil  2020-02-28          1.0        0.0   
3      BRA  South America   Brazil  2020-02-29          2.0        1.0   
4      BRA  South America   Brazil  2020-03-01          2.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
0                 NaN           NaN         NaN                  NaN   
1                 NaN           NaN         NaN                  NaN   
2                 NaN           NaN         NaN                  NaN   
3                 NaN           NaN         NaN                  NaN   
4                 NaN           NaN         NaN                  NaN   

   total_cases_per_million  new_cases_per_million  \
0                    0.005                  0.005   
1                    0.005                  0.000   
2                    0.005                  0.000   
3                    0.009                  0.005   
4                    0.009                  0.000   

   new_cases_smoothed_per_million  total_deaths_per_million  \
0                             NaN                       NaN   
1                             NaN                       NaN   
2                             NaN                       NaN   
3                             NaN                       NaN   
4                             NaN                       NaN   

   new_deaths_per_million  new_deaths_smoothed_per_million  reproduction_rate  \
0                     NaN                              NaN                NaN   
1                     NaN                              NaN                NaN   
2                     NaN                              NaN                NaN   
3                     NaN                              NaN                NaN   
4                     NaN                              NaN                NaN   

   icu_patients  icu_patients_per_million  hosp_patients  \
0           NaN                       NaN            NaN   
1           NaN                       NaN            NaN   
2           NaN                       NaN            NaN   
3           NaN                       NaN            NaN   
4           NaN                       NaN            NaN   

   hosp_patients_per_million  weekly_icu_admissions  \
0                        NaN                    NaN   
1                        NaN                    NaN   
2                        NaN                    NaN   
3                        NaN                    NaN   
4                        NaN                    NaN   

   weekly_icu_admissions_per_million  weekly_hosp_admissions  \
0                                NaN                     NaN   
1                                NaN                     NaN   
2                                NaN                     NaN   
3                                NaN                     NaN   
4                                NaN                     NaN   

   weekly_hosp_admissions_per_million  new_tests  total_tests  \
0                                 NaN        NaN          NaN   
1                                 NaN        NaN          NaN   
2                                 NaN        NaN          NaN   
3                                 NaN        NaN          NaN   
4                                 NaN        NaN          NaN   

   total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  \
0                       NaN                     NaN                 NaN   
1                       NaN                     NaN                 NaN   
2                       NaN                     NaN                 NaN   
3                       NaN                     NaN                 NaN   
4                       NaN                     NaN                 NaN   

   new_tests_smoothe

Utilizando a função `.iloc` podemos selecionar linhas e colunas com os índices numéricos. E se quisermos, por exemplo, comparar o número total de casos de todos os países ao longo do tempo, mantendo apenas as variáveis `location`, `date` e `total_cases`?

In [18]:
df_covid.iloc[:,2:5]

location        date  total_cases
0            Brazil  2020-02-26          1.0
1            Brazil  2020-02-27          1.0
2            Brazil  2020-02-28          1.0
3            Brazil  2020-02-29          2.0
4            Brazil  2020-03-01          2.0
...             ...         ...          ...
7658  United States  2022-03-01   79091361.0
7659  United States  2022-03-02   79143716.0
7660  United States  2022-03-03   79196008.0
7661  United States  2022-03-04   79250509.0
7662  United States  2022-03-05   79265726.0

[7663 rows x 3 columns]

Podemos fazer exatamente a mesma coisa com a função `.loc` e utilizando uma mistura de índices numéricos para as linhas e seleção das colunas através de seus nomes.

In [19]:
df_covid.loc[:, ['location','date','total_cases']]

location        date  total_cases
0            Brazil  2020-02-26          1.0
1            Brazil  2020-02-27          1.0
2            Brazil  2020-02-28          1.0
3            Brazil  2020-02-29          2.0
4            Brazil  2020-03-01          2.0
...             ...         ...          ...
7658  United States  2022-03-01   79091361.0
7659  United States  2022-03-02   79143716.0
7660  United States  2022-03-03   79196008.0
7661  United States  2022-03-04   79250509.0
7662  United States  2022-03-05   79265726.0

[7663 rows x 3 columns]

Uma terceira forma de fazer esse exercício de seleção de uma parte de um DataFrame já criado é através da criação de um novo DataFrame que mantenha apenas as colunas `location`, `date` e `total_cases`.

In [20]:
columns_to_keep = ['location','date','total_cases']
df_covid2 = df_covid[columns_to_keep]

df_covid2.head()

location        date  total_cases
0   Brazil  2020-02-26          1.0
1   Brazil  2020-02-27          1.0
2   Brazil  2020-02-28          1.0
3   Brazil  2020-02-29          2.0
4   Brazil  2020-03-01          2.0

Podemos inclusive alterar o nome das colunas desse novo DataFrame de forma bem direta.

In [21]:
df_covid2.columns = ['localizacao','data','casos']
df_covid2.head()

localizacao        data  casos
0      Brazil  2020-02-26    1.0
1      Brazil  2020-02-27    1.0
2      Brazil  2020-02-28    1.0
3      Brazil  2020-02-29    2.0
4      Brazil  2020-03-01    2.0

É possível redefinir o índice desse novo DataFrame para ser igual ao país.

In [22]:
df_covid2.set_index('localizacao', inplace=True)
df_covid2.head()

data  casos
localizacao                   
Brazil       2020-02-26    1.0
Brazil       2020-02-27    1.0
Brazil       2020-02-28    1.0
Brazil       2020-02-29    2.0
Brazil       2020-03-01    2.0

Por fim, podemos selecionar parte específica de um DataFrame utilizando testes booleanos sobre valores de linhas e colunas.

* Selecionar apenas os dados brasileiros

In [23]:
df_covid[df_covid['location']=='Brazil']

iso_code      continent location        date  total_cases  new_cases  \
0        BRA  South America   Brazil  2020-02-26          1.0        1.0   
1        BRA  South America   Brazil  2020-02-27          1.0        0.0   
2        BRA  South America   Brazil  2020-02-28          1.0        0.0   
3        BRA  South America   Brazil  2020-02-29          2.0        1.0   
4        BRA  South America   Brazil  2020-03-01          2.0        0.0   
..       ...            ...      ...         ...          ...        ...   
734      BRA  South America   Brazil  2022-03-01   28818850.0    22279.0   
735      BRA  South America   Brazil  2022-03-02   28846495.0    27645.0   
736      BRA  South America   Brazil  2022-03-03   28906672.0    60177.0   
737      BRA  South America   Brazil  2022-03-04   28978052.0    71380.0   
738      BRA  South America   Brazil  2022-03-05   29040800.0    62748.0   

     new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
0                   NaN           NaN         NaN                  NaN   
1                   NaN           NaN         NaN                  NaN   
2                   NaN           NaN         NaN                  NaN   
3                   NaN           NaN         NaN                  NaN   
4                   NaN           NaN         NaN                  NaN   
..                  ...           ...         ...                  ...   
734           65271.286      649922.0       246.0              598.143   
735           50451.286      650254.0       332.0              505.714   
736           45348.143      650824.0       570.0              445.857   
737           42625.857      651522.0       698.0              432.286   
738           41606.857      652216.0       694.0              433.143   

     total_cases_per_million  new_cases_per_million  \
0                      0.005                  0.005   
1                      0.005                  0.000   
2                      0.005                  0.000   
3                      0.009                  0.005   
4                      0.009                  0.000   
..                       ...                    ...   
734               134671.651                104.111   
735               134800.837                129.186   
736               135082.047                281.210   
737               135415.608                333.562   
738               135708.832                293.224   

     new_cases_smoothed_per_million  total_deaths_per_million  \
0                               NaN                       NaN   
1                               NaN                       NaN   
2                               NaN                       NaN   
3                               NaN                       NaN   
4                               NaN                       NaN   
..                              ...                       ...   
734                         305.015                  3037.112   
735                         235.761                  3038.663   
736                         211.914                  3041.327   
737                         199.192                  3044.589   
738                         194.431                  3047.832   

     new_deaths_per_million  new_deaths_smoothed_per_million  \
0                       NaN                              NaN   
1                       NaN                              NaN   
2                       NaN                              NaN   
3                       NaN                              NaN   
4                       NaN                              NaN   
..                      ...                              ...   
734                   1.150                            2.795   
735                   1.551                            2.363   
736                   2.664                            2.084   
737                   3.262                            2.020   
738                   3.243                            2

* Selecionar os dados brasileiros e apenas à partir do momento em que o número de casos se tornou maior do que 10 milhões

In [24]:
df_covid[(df_covid['location']=='Brazil') & (df_covid['total_cases']>=10000000)]

iso_code      continent location        date  total_cases  new_cases  \
358      BRA  South America   Brazil  2021-02-18   10039804.0    53479.0   
359      BRA  South America   Brazil  2021-02-19   10091961.0    52157.0   
360      BRA  South America   Brazil  2021-02-20   10144332.0    52371.0   
361      BRA  South America   Brazil  2021-02-21   10173817.0    29485.0   
362      BRA  South America   Brazil  2021-02-22   10205663.0    31846.0   
..       ...            ...      ...         ...          ...        ...   
734      BRA  South America   Brazil  2022-03-01   28818850.0    22279.0   
735      BRA  South America   Brazil  2022-03-02   28846495.0    27645.0   
736      BRA  South America   Brazil  2022-03-03   28906672.0    60177.0   
737      BRA  South America   Brazil  2022-03-04   28978052.0    71380.0   
738      BRA  South America   Brazil  2022-03-05   29040800.0    62748.0   

     new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
358           45188.143      243752.0      1439.0             1032.714   
359           45647.429      245083.0      1331.0             1048.571   
360           46721.000      246114.0      1031.0             1049.429   
361           46544.143      246720.0       606.0             1042.714   
362           47406.714      247431.0       711.0             1057.000   
..                  ...           ...         ...                  ...   
734           65271.286      649922.0       246.0              598.143   
735           50451.286      650254.0       332.0              505.714   
736           45348.143      650824.0       570.0              445.857   
737           42625.857      651522.0       698.0              432.286   
738           41606.857      652216.0       694.0              433.143   

     total_cases_per_million  new_cases_per_million  \
358                46916.410                249.910   
359                47160.142                243.732   
360                47404.873                244.732   
361                47542.658                137.785   
362                47691.476                148.818   
..                       ...                    ...   
734               134671.651                104.111   
735               134800.837                129.186   
736               135082.047                281.210   
737               135415.608                333.562   
738               135708.832                293.224   

     new_cases_smoothed_per_million  total_deaths_per_million  \
358                         211.166                  1139.063   
359                         213.312                  1145.283   
360                         218.329                  1150.101   
361                         217.503                  1152.933   
362                         221.533                  1156.255   
..                              ...                       ...   
734                         305.015                  3037.112   
735                         235.761                  3038.663   
736                         211.914                  3041.327   
737                         199.192                  3044.589   
738                         194.431                  3047.832   

     new_deaths_per_million  new_deaths_smoothed_per_million  \
358                   6.725                            4.826   
359                   6.220                            4.900   
360                   4.818                            4.904   
361                   2.832                            4.873   
362                   3.323                            4.939   
..                      ...                              ...   
734                   1.150                            2.795   
735                   1.551                            2.363   
736                   2.664                            2.084   
737                   3.262                            2.020   
738                   3.243                            2

* Selecionar os dados do Brasil e Estados Unidos

In [25]:
df_covid[df_covid['iso_code'].isin(['BRA','USA'])]

iso_code      continent       location        date  total_cases  \
0         BRA  South America         Brazil  2020-02-26          1.0   
1         BRA  South America         Brazil  2020-02-27          1.0   
2         BRA  South America         Brazil  2020-02-28          1.0   
3         BRA  South America         Brazil  2020-02-29          2.0   
4         BRA  South America         Brazil  2020-03-01          2.0   
...       ...            ...            ...         ...          ...   
7658      USA  North America  United States  2022-03-01   79091361.0   
7659      USA  North America  United States  2022-03-02   79143716.0   
7660      USA  North America  United States  2022-03-03   79196008.0   
7661      USA  North America  United States  2022-03-04   79250509.0   
7662      USA  North America  United States  2022-03-05   79265726.0   

      new_cases  new_cases_smoothed  total_deaths  new_deaths  \
0           1.0                 NaN           NaN         NaN   
1           0.0                 NaN           NaN         NaN   
2           0.0                 NaN           NaN         NaN   
3           1.0                 NaN           NaN         NaN   
4           0.0                 NaN           NaN         NaN   
...         ...                 ...           ...         ...   
7658    47031.0           62331.429      952423.0      1691.0   
7659    52355.0           57824.857      954518.0      2095.0   
7660    52292.0           55673.857      956261.0      1743.0   
7661    54501.0           52764.286      958144.0      1883.0   
7662    15217.0           47989.857      958437.0       293.0   

      new_deaths_smoothed  total_cases_per_million  new_cases_per_million  \
0                     NaN                    0.005                  0.005   
1                     NaN                    0.005                  0.000   
2                     NaN                    0.005                  0.000   
3                     NaN                    0.009                  0.005   
4                     NaN                    0.009                  0.000   
...                   ...                      ...                    ...   
7658             1830.000               237572.183                141.270   
7659             1725.000               237729.446                157.262   
7660             1553.714               237886.519                157.073   
7661             1497.857               238050.227                163.708   
7662             1425.714               238095.936                 45.708   

      new_cases_smoothed_per_million  total_deaths_per_million  \
0                                NaN                       NaN   
1                                NaN                       NaN   
2                                NaN                       NaN   
3                                NaN                       NaN   
4                                NaN                       NaN   
...                              ...                       ...   
7658                         187.229                  2860.859   
7659                         173.693                  2867.152   
7660                         167.231                  2872.387   
7661                         158.492                  2878.043   
7662                         144.150                  2878.923   

      new_deaths_per_million  new_deaths_smoothed_per_million  \
0                        NaN                              NaN   
1                        NaN                              NaN   
2                        NaN                              NaN   
3                        NaN                              NaN   
4                        NaN                              NaN   
...                      ...                              ...   
7658                   5.079                            5.497   
7659                   6.293                            5.182   
7660                   5.236                            

## Operações com colunas numéricas


Criar novas colunas a partir de operações sobre aquelas que já existem é bastante simples. Vamos primeiro aumentar o número de linhas que são mostradas por padrão justamente para que possamos ver etapa por etapa. Além disso, vamos manter apenas os dados para o Brasil para melhor visualizar os resultados.

In [26]:
pd.set_option('display.max_rows', 1000)
df_covid_br = df_covid[df_covid['iso_code']=='BRA'].reset_index()

Agora já podemos brincar com as colunas numéricas e mostrar o resultado dos cálculos.

* Coluna com o aumento percentual de casos a cada dia

In [27]:
df_covid_br['new_cases_percentage'] = df_covid_br['new_cases'] / df_covid_br['total_cases']

columns_to_show = ['date','total_cases','new_cases','new_cases_percentage']
df_covid_br[columns_to_show]

date  total_cases  new_cases  new_cases_percentage
0    2020-02-26          1.0        1.0              1.000000
1    2020-02-27          1.0        0.0              0.000000
2    2020-02-28          1.0        0.0              0.000000
3    2020-02-29          2.0        1.0              0.500000
4    2020-03-01          2.0        0.0              0.000000
5    2020-03-02          2.0        0.0              0.000000
6    2020-03-03          2.0        0.0              0.000000
7    2020-03-04          4.0        2.0              0.500000
8    2020-03-05          4.0        0.0              0.000000
9    2020-03-06         13.0        9.0              0.692308
10   2020-03-07         13.0        0.0              0.000000
11   2020-03-08         20.0        7.0              0.350000
12   2020-03-09         25.0        5.0              0.200000
13   2020-03-10         31.0        6.0              0.193548
14   2020-03-11         38.0        7.0              0.184211
15   2020-03-12         52.0       14.0              0.269231
16   2020-03-13        151.0       99.0              0.655629
17   2020-03-14        151.0        0.0              0.000000
18   2020-03-15        162.0       11.0              0.067901
19   2020-03-16        200.0       38.0              0.190000
20   2020-03-17        321.0      121.0              0.376947
21   2020-03-18        372.0       51.0              0.137097
22   2020-03-19        621.0      249.0              0.400966
23   2020-03-20        793.0      172.0              0.216898
24   2020-03-21       1021.0      228.0              0.223310
25   2020-03-22       1546.0      525.0              0.339586
26   2020-03-23       1924.0      378.0              0.196466
27   2020-03-24       2247.0      323.0              0.143747
28   2020-03-25       2554.0      307.0              0.120204
29   2020-03-26       2985.0      431.0              0.144389
30   2020-03-27       3417.0      432.0              0.126427
31   2020-03-28       3904.0      487.0              0.124744
32   2020-03-29       4256.0      352.0              0.082707
33   2020-03-30       4579.0      323.0              0.070539
34   2020-03-31       5717.0     1138.0              0.199055
35   2020-04-01       6836.0     1119.0              0.163692
36   2020-04-02       8044.0     1208.0              0.150174
37   2020-04-03       9056.0     1012.0              0.111749
38   2020-04-04      10360.0     1304.0              0.125869
39   2020-04-05      11130.0      770.0              0.069182
40   2020-04-06      12161.0     1031.0              0.084779
41   2020-04-07      14034.0     1873.0              0.133462
42   2020-04-08      16170.0     2136.0              0.132096
43   2020-04-09      18092.0     1922.0              0.106235
44   2020-04-10      19638.0     1546.0              0.078725
45   2020-04-11      20727.0     1089.0              0.052540
46   2020-04-12      22192.0     1465.0              0.066015
47   2020-04-13      23430.0     1238.0              0.052838
48   2020-04-14      25262.0     1832.0              0.072520
49   2020-04-15      28320.0     3058.0              0.107980
50   2020-04-16      30425.0     2105.0              0.069187
51   2020-04-17      33682.0     3257.0              0.096699
52   2020-04-18      36658.0     2976.0              0.081183
53   2020-04-19      38654.0     1996.0              0.051638
54   2020-04-20      40743.0     2089.0              0.051273
55   2020-04-21      43079.0     2336.0              0.054226
56   2020-04-22      45757.0     2678.0              0.058527
57   2020-04-23      50036.0     4279.0              0.085518
58   2020-04-24      54043.0     4007.0              0.074145
59   2020-04-25      59324.0     5281.0              0.089020
60   2020-04-26      63100.0     3776.0              0.059842
61   2020-04-27      67446.0     4346.0              0.064437
62   2020-04-28      73235.0     5789.0              0.079047
63   2020-04-29      79685.0     6450.0    

* Coluna com o log do total de casos

In [28]:
df_covid_br['log_total_cases'] = np.log(df_covid_br['total_cases'])

columns_to_show = ['date','total_cases','log_total_cases']
df_covid_br[columns_to_show]

date  total_cases  log_total_cases
0    2020-02-26          1.0         0.000000
1    2020-02-27          1.0         0.000000
2    2020-02-28          1.0         0.000000
3    2020-02-29          2.0         0.693147
4    2020-03-01          2.0         0.693147
5    2020-03-02          2.0         0.693147
6    2020-03-03          2.0         0.693147
7    2020-03-04          4.0         1.386294
8    2020-03-05          4.0         1.386294
9    2020-03-06         13.0         2.564949
10   2020-03-07         13.0         2.564949
11   2020-03-08         20.0         2.995732
12   2020-03-09         25.0         3.218876
13   2020-03-10         31.0         3.433987
14   2020-03-11         38.0         3.637586
15   2020-03-12         52.0         3.951244
16   2020-03-13        151.0         5.017280
17   2020-03-14        151.0         5.017280
18   2020-03-15        162.0         5.087596
19   2020-03-16        200.0         5.298317
20   2020-03-17        321.0         5.771441
21   2020-03-18        372.0         5.918894
22   2020-03-19        621.0         6.431331
23   2020-03-20        793.0         6.675823
24   2020-03-21       1021.0         6.928538
25   2020-03-22       1546.0         7.343426
26   2020-03-23       1924.0         7.562162
27   2020-03-24       2247.0         7.717351
28   2020-03-25       2554.0         7.845416
29   2020-03-26       2985.0         8.001355
30   2020-03-27       3417.0         8.136518
31   2020-03-28       3904.0         8.269757
32   2020-03-29       4256.0         8.356085
33   2020-03-30       4579.0         8.429236
34   2020-03-31       5717.0         8.651199
35   2020-04-01       6836.0         8.829958
36   2020-04-02       8044.0         8.992682
37   2020-04-03       9056.0         9.111183
38   2020-04-04      10360.0         9.245708
39   2020-04-05      11130.0         9.317399
40   2020-04-06      12161.0         9.405989
41   2020-04-07      14034.0         9.549238
42   2020-04-08      16170.0         9.690913
43   2020-04-09      18092.0         9.803225
44   2020-04-10      19638.0         9.885222
45   2020-04-11      20727.0         9.939192
46   2020-04-12      22192.0        10.007487
47   2020-04-13      23430.0        10.061773
48   2020-04-14      25262.0        10.137057
49   2020-04-15      28320.0        10.251324
50   2020-04-16      30425.0        10.323020
51   2020-04-17      33682.0        10.424719
52   2020-04-18      36658.0        10.509387
53   2020-04-19      38654.0        10.562406
54   2020-04-20      40743.0        10.615039
55   2020-04-21      43079.0        10.670791
56   2020-04-22      45757.0        10.731100
57   2020-04-23      50036.0        10.820498
58   2020-04-24      54043.0        10.897535
59   2020-04-25      59324.0        10.990769
60   2020-04-26      63100.0        11.052476
61   2020-04-27      67446.0        11.119083
62   2020-04-28      73235.0        11.201429
63   2020-04-29      79685.0        11.285837
64   2020-04-30      87187.0        11.375811
65   2020-05-01      92202.0        11.431737
66   2020-05-02      97100.0        11.483497
67   2020-05-03     101826.0        11.531021
68   2020-05-04     108620.0        11.595611
69   2020-05-05     115455.0        11.656636
70   2020-05-06     126611.0        11.748875
71   2020-05-07     135773.0        11.818740
72   2020-05-08     146894.0        11.897467
73   2020-05-09     156061.0        11.958002
74   2020-05-10     162699.0        11.999657
75   2020-05-11     169594.0        12.041163
76   2020-05-12     178214.0        12.090740
77   2020-05-13     190137.0        12.155500
78   2020-05-14     203165.0        12.221774
79   2020-05-15     220291.0        12.302705
80   2020-05-16     233511.0        12.360984
81   2020-05-17     241080.0        12.392884
82   2020-05-18     255368.0        12.450461
83   2020-05-19     271885.0        12.513134
84   2020-05-20     294624.0        12.593455
85   2020-05-21     312761.0        12.653195
86   2020

* Coluna com o total de casos em milhares

In [29]:
df_covid_br['total_cases_th'] = df_covid_br['total_cases'] / 1000

columns_to_show = ['date','total_cases','total_cases_th']
df_covid_br[columns_to_show]

date  total_cases  total_cases_th
0    2020-02-26          1.0           0.001
1    2020-02-27          1.0           0.001
2    2020-02-28          1.0           0.001
3    2020-02-29          2.0           0.002
4    2020-03-01          2.0           0.002
5    2020-03-02          2.0           0.002
6    2020-03-03          2.0           0.002
7    2020-03-04          4.0           0.004
8    2020-03-05          4.0           0.004
9    2020-03-06         13.0           0.013
10   2020-03-07         13.0           0.013
11   2020-03-08         20.0           0.020
12   2020-03-09         25.0           0.025
13   2020-03-10         31.0           0.031
14   2020-03-11         38.0           0.038
15   2020-03-12         52.0           0.052
16   2020-03-13        151.0           0.151
17   2020-03-14        151.0           0.151
18   2020-03-15        162.0           0.162
19   2020-03-16        200.0           0.200
20   2020-03-17        321.0           0.321
21   2020-03-18        372.0           0.372
22   2020-03-19        621.0           0.621
23   2020-03-20        793.0           0.793
24   2020-03-21       1021.0           1.021
25   2020-03-22       1546.0           1.546
26   2020-03-23       1924.0           1.924
27   2020-03-24       2247.0           2.247
28   2020-03-25       2554.0           2.554
29   2020-03-26       2985.0           2.985
30   2020-03-27       3417.0           3.417
31   2020-03-28       3904.0           3.904
32   2020-03-29       4256.0           4.256
33   2020-03-30       4579.0           4.579
34   2020-03-31       5717.0           5.717
35   2020-04-01       6836.0           6.836
36   2020-04-02       8044.0           8.044
37   2020-04-03       9056.0           9.056
38   2020-04-04      10360.0          10.360
39   2020-04-05      11130.0          11.130
40   2020-04-06      12161.0          12.161
41   2020-04-07      14034.0          14.034
42   2020-04-08      16170.0          16.170
43   2020-04-09      18092.0          18.092
44   2020-04-10      19638.0          19.638
45   2020-04-11      20727.0          20.727
46   2020-04-12      22192.0          22.192
47   2020-04-13      23430.0          23.430
48   2020-04-14      25262.0          25.262
49   2020-04-15      28320.0          28.320
50   2020-04-16      30425.0          30.425
51   2020-04-17      33682.0          33.682
52   2020-04-18      36658.0          36.658
53   2020-04-19      38654.0          38.654
54   2020-04-20      40743.0          40.743
55   2020-04-21      43079.0          43.079
56   2020-04-22      45757.0          45.757
57   2020-04-23      50036.0          50.036
58   2020-04-24      54043.0          54.043
59   2020-04-25      59324.0          59.324
60   2020-04-26      63100.0          63.100
61   2020-04-27      67446.0          67.446
62   2020-04-28      73235.0          73.235
63   2020-04-29      79685.0          79.685
64   2020-04-30      87187.0          87.187
65   2020-05-01      92202.0          92.202
66   2020-05-02      97100.0          97.100
67   2020-05-03     101826.0         101.826
68   2020-05-04     108620.0         108.620
69   2020-05-05     115455.0         115.455
70   2020-05-06     126611.0         126.611
71   2020-05-07     135773.0         135.773
72   2020-05-08     146894.0         146.894
73   2020-05-09     156061.0         156.061
74   2020-05-10     162699.0         162.699
75   2020-05-11     169594.0         169.594
76   2020-05-12     178214.0         178.214
77   2020-05-13     190137.0         190.137
78   2020-05-14     203165.0         203.165
79   2020-05-15     220291.0         220.291
80   2020-05-16     233511.0         233.511
81   2020-05-17     241080.0         241.080
82   2020-05-18     255368.0         255.368
83   2020-05-19     271885.0         271.885
84   2020-05-20     294624.0         294.624
85   2020-05-21     312761.0         312.761
86   2020-05-22     334568.0         334.568
87   2020-05-23     351565.0         351.565
88   2

* Subtrair a média do número de novos casos da coluna de novos casos para encontrar o desvio em relação à média.

In [30]:
df_covid_br['new_cases_demean'] = df_covid_br['new_cases'] - df_covid_br['new_cases'].mean()

columns_to_show = ['date','new_cases','new_cases_demean']
df_covid_br[columns_to_show]

date  new_cases  new_cases_demean
0    2020-02-26        1.0     -39260.489824
1    2020-02-27        0.0     -39261.489824
2    2020-02-28        0.0     -39261.489824
3    2020-02-29        1.0     -39260.489824
4    2020-03-01        0.0     -39261.489824
5    2020-03-02        0.0     -39261.489824
6    2020-03-03        0.0     -39261.489824
7    2020-03-04        2.0     -39259.489824
8    2020-03-05        0.0     -39261.489824
9    2020-03-06        9.0     -39252.489824
10   2020-03-07        0.0     -39261.489824
11   2020-03-08        7.0     -39254.489824
12   2020-03-09        5.0     -39256.489824
13   2020-03-10        6.0     -39255.489824
14   2020-03-11        7.0     -39254.489824
15   2020-03-12       14.0     -39247.489824
16   2020-03-13       99.0     -39162.489824
17   2020-03-14        0.0     -39261.489824
18   2020-03-15       11.0     -39250.489824
19   2020-03-16       38.0     -39223.489824
20   2020-03-17      121.0     -39140.489824
21   2020-03-18       51.0     -39210.489824
22   2020-03-19      249.0     -39012.489824
23   2020-03-20      172.0     -39089.489824
24   2020-03-21      228.0     -39033.489824
25   2020-03-22      525.0     -38736.489824
26   2020-03-23      378.0     -38883.489824
27   2020-03-24      323.0     -38938.489824
28   2020-03-25      307.0     -38954.489824
29   2020-03-26      431.0     -38830.489824
30   2020-03-27      432.0     -38829.489824
31   2020-03-28      487.0     -38774.489824
32   2020-03-29      352.0     -38909.489824
33   2020-03-30      323.0     -38938.489824
34   2020-03-31     1138.0     -38123.489824
35   2020-04-01     1119.0     -38142.489824
36   2020-04-02     1208.0     -38053.489824
37   2020-04-03     1012.0     -38249.489824
38   2020-04-04     1304.0     -37957.489824
39   2020-04-05      770.0     -38491.489824
40   2020-04-06     1031.0     -38230.489824
41   2020-04-07     1873.0     -37388.489824
42   2020-04-08     2136.0     -37125.489824
43   2020-04-09     1922.0     -37339.489824
44   2020-04-10     1546.0     -37715.489824
45   2020-04-11     1089.0     -38172.489824
46   2020-04-12     1465.0     -37796.489824
47   2020-04-13     1238.0     -38023.489824
48   2020-04-14     1832.0     -37429.489824
49   2020-04-15     3058.0     -36203.489824
50   2020-04-16     2105.0     -37156.489824
51   2020-04-17     3257.0     -36004.489824
52   2020-04-18     2976.0     -36285.489824
53   2020-04-19     1996.0     -37265.489824
54   2020-04-20     2089.0     -37172.489824
55   2020-04-21     2336.0     -36925.489824
56   2020-04-22     2678.0     -36583.489824
57   2020-04-23     4279.0     -34982.489824
58   2020-04-24     4007.0     -35254.489824
59   2020-04-25     5281.0     -33980.489824
60   2020-04-26     3776.0     -35485.489824
61   2020-04-27     4346.0     -34915.489824
62   2020-04-28     5789.0     -33472.489824
63   2020-04-29     6450.0     -32811.489824
64   2020-04-30     7502.0     -31759.489824
65   2020-05-01     5015.0     -34246.489824
66   2020-05-02     4898.0     -34363.489824
67   2020-05-03     4726.0     -34535.489824
68   2020-05-04     6794.0     -32467.489824
69   2020-05-05     6835.0     -32426.489824
70   2020-05-06    11156.0     -28105.489824
71   2020-05-07     9162.0     -30099.489824
72   2020-05-08    11121.0     -28140.489824
73   2020-05-09     9167.0     -30094.489824
74   2020-05-10     6638.0     -32623.489824
75   2020-05-11     6895.0     -32366.489824
76   2020-05-12     8620.0     -30641.489824
77   2020-05-13    11923.0     -27338.489824
78   2020-05-14    13028.0     -26233.489824
79   2020-05-15    17126.0     -22135.489824
80   2020-05-16    13220.0     -26041.489824
81   2020-05-17     7569.0     -31692.489824
82   2020-05-18    14288.0     -24973.489824
83   2020-05-19    16517.0     -22744.489824
84   2020-05-20    22739.0     -16522.489824
85   2020-05-21    18137.0     -21124.489824
86   2020-05-22    21807.0     -17454.489824
87   2020-05-23    16997.0     -22264.489824
88   2

Para realizar outras operações simples de soma, subtração, multiplicação e divisão a lógica é a mesma, independente de ser uma operação entre colunas ou de uma coluna com um escalar. Para operações mais complexas, no entanto, o método `.apply` em conjunto com funções anônimas do tipo `lambda` constituem uma ferramenta poderosíssima.

* Elevar o número de novos casos ao quadrado e dividir o resultado por 1 milhão.

In [31]:
df_covid_br['total_cases_sq'] = df_covid_br['total_cases'].apply(lambda x: (x**2)/ 1e6)

columns_to_show = ['date','total_cases','total_cases_sq']
df_covid_br[columns_to_show]

date  total_cases  total_cases_sq
0    2020-02-26          1.0    1.000000e-06
1    2020-02-27          1.0    1.000000e-06
2    2020-02-28          1.0    1.000000e-06
3    2020-02-29          2.0    4.000000e-06
4    2020-03-01          2.0    4.000000e-06
5    2020-03-02          2.0    4.000000e-06
6    2020-03-03          2.0    4.000000e-06
7    2020-03-04          4.0    1.600000e-05
8    2020-03-05          4.0    1.600000e-05
9    2020-03-06         13.0    1.690000e-04
10   2020-03-07         13.0    1.690000e-04
11   2020-03-08         20.0    4.000000e-04
12   2020-03-09         25.0    6.250000e-04
13   2020-03-10         31.0    9.610000e-04
14   2020-03-11         38.0    1.444000e-03
15   2020-03-12         52.0    2.704000e-03
16   2020-03-13        151.0    2.280100e-02
17   2020-03-14        151.0    2.280100e-02
18   2020-03-15        162.0    2.624400e-02
19   2020-03-16        200.0    4.000000e-02
20   2020-03-17        321.0    1.030410e-01
21   2020-03-18        372.0    1.383840e-01
22   2020-03-19        621.0    3.856410e-01
23   2020-03-20        793.0    6.288490e-01
24   2020-03-21       1021.0    1.042441e+00
25   2020-03-22       1546.0    2.390116e+00
26   2020-03-23       1924.0    3.701776e+00
27   2020-03-24       2247.0    5.049009e+00
28   2020-03-25       2554.0    6.522916e+00
29   2020-03-26       2985.0    8.910225e+00
30   2020-03-27       3417.0    1.167589e+01
31   2020-03-28       3904.0    1.524122e+01
32   2020-03-29       4256.0    1.811354e+01
33   2020-03-30       4579.0    2.096724e+01
34   2020-03-31       5717.0    3.268409e+01
35   2020-04-01       6836.0    4.673090e+01
36   2020-04-02       8044.0    6.470594e+01
37   2020-04-03       9056.0    8.201114e+01
38   2020-04-04      10360.0    1.073296e+02
39   2020-04-05      11130.0    1.238769e+02
40   2020-04-06      12161.0    1.478899e+02
41   2020-04-07      14034.0    1.969532e+02
42   2020-04-08      16170.0    2.614689e+02
43   2020-04-09      18092.0    3.273205e+02
44   2020-04-10      19638.0    3.856510e+02
45   2020-04-11      20727.0    4.296085e+02
46   2020-04-12      22192.0    4.924849e+02
47   2020-04-13      23430.0    5.489649e+02
48   2020-04-14      25262.0    6.381686e+02
49   2020-04-15      28320.0    8.020224e+02
50   2020-04-16      30425.0    9.256806e+02
51   2020-04-17      33682.0    1.134477e+03
52   2020-04-18      36658.0    1.343809e+03
53   2020-04-19      38654.0    1.494132e+03
54   2020-04-20      40743.0    1.659992e+03
55   2020-04-21      43079.0    1.855800e+03
56   2020-04-22      45757.0    2.093703e+03
57   2020-04-23      50036.0    2.503601e+03
58   2020-04-24      54043.0    2.920646e+03
59   2020-04-25      59324.0    3.519337e+03
60   2020-04-26      63100.0    3.981610e+03
61   2020-04-27      67446.0    4.548963e+03
62   2020-04-28      73235.0    5.363365e+03
63   2020-04-29      79685.0    6.349699e+03
64   2020-04-30      87187.0    7.601573e+03
65   2020-05-01      92202.0    8.501209e+03
66   2020-05-02      97100.0    9.428410e+03
67   2020-05-03     101826.0    1.036853e+04
68   2020-05-04     108620.0    1.179830e+04
69   2020-05-05     115455.0    1.332986e+04
70   2020-05-06     126611.0    1.603035e+04
71   2020-05-07     135773.0    1.843431e+04
72   2020-05-08     146894.0    2.157785e+04
73   2020-05-09     156061.0    2.435504e+04
74   2020-05-10     162699.0    2.647096e+04
75   2020-05-11     169594.0    2.876212e+04
76   2020-05-12     178214.0    3.176023e+04
77   2020-05-13     190137.0    3.615208e+04
78   2020-05-14     203165.0    4.127602e+04
79   2020-05-15     220291.0    4.852812e+04
80   2020-05-16     233511.0    5.452739e+04
81   2020-05-17     241080.0    5.811957e+04
82   2020-05-18     255368.0    6.521282e+04
83   2020-05-19     271885.0    7.392145e+04
84   2020-05-20     294624.0    8.680330e+04
85   2020-05-21     312761.0    9.781944e+04
86   2020-05-22     334568.0    1.119357e+05
87   2020-05-23     351565.0    1.235979e+05
88   2

Para visualizar melhor, vamos focar no último valor, representado pelo índice 738.

In [32]:
print(df_covid_br.loc[738,'total_cases'])
print(df_covid_br.loc[738,'total_cases_sq'])
print((df_covid_br.loc[738,'total_cases'] ** 2) / 1000000)

29040800.0
843368064.64
843368064.64


Dei apenas exemplos super simples, mas note a força que o método `apply` tem quando trabalhado em conjunto com as funções `lambda`. O céu é o limite.

## Operações com colunas contendo strings

O Pandas também nos fornece métodos e funções bastante interessantes para trabalhar com dados do tipo `string`. Vamos começar com um exemplo simples: transformando a nossa coluna com o nome dos países para um coluna com letras minúsculas apenas.

In [33]:
df_covid_br['lower_location'] = df_covid_br['location'].lower()

AttributeError: 'Series' object has no attribute 'lower'

Ué, mas não era só usar os métodos de strings que já utilizamos já que a coluna tem esse formato? Para trabalhar com essas funções/métodos precisamos primeiro dizer ao Pandas que a coluna de interesse receberá operações específicas a strings.

In [34]:
df_covid_br['lower_location'] = df_covid_br['location'].str.lower()

columns_to_show = ['iso_code','continent','location','lower_location','date']
df_covid_br[columns_to_show]

iso_code      continent location lower_location        date
0        BRA  South America   Brazil         brazil  2020-02-26
1        BRA  South America   Brazil         brazil  2020-02-27
2        BRA  South America   Brazil         brazil  2020-02-28
3        BRA  South America   Brazil         brazil  2020-02-29
4        BRA  South America   Brazil         brazil  2020-03-01
5        BRA  South America   Brazil         brazil  2020-03-02
6        BRA  South America   Brazil         brazil  2020-03-03
7        BRA  South America   Brazil         brazil  2020-03-04
8        BRA  South America   Brazil         brazil  2020-03-05
9        BRA  South America   Brazil         brazil  2020-03-06
10       BRA  South America   Brazil         brazil  2020-03-07
11       BRA  South America   Brazil         brazil  2020-03-08
12       BRA  South America   Brazil         brazil  2020-03-09
13       BRA  South America   Brazil         brazil  2020-03-10
14       BRA  South America   Brazil         brazil  2020-03-11
15       BRA  South America   Brazil         brazil  2020-03-12
16       BRA  South America   Brazil         brazil  2020-03-13
17       BRA  South America   Brazil         brazil  2020-03-14
18       BRA  South America   Brazil         brazil  2020-03-15
19       BRA  South America   Brazil         brazil  2020-03-16
20       BRA  South America   Brazil         brazil  2020-03-17
21       BRA  South America   Brazil         brazil  2020-03-18
22       BRA  South America   Brazil         brazil  2020-03-19
23       BRA  South America   Brazil         brazil  2020-03-20
24       BRA  South America   Brazil         brazil  2020-03-21
25       BRA  South America   Brazil         brazil  2020-03-22
26       BRA  South America   Brazil         brazil  2020-03-23
27       BRA  South America   Brazil         brazil  2020-03-24
28       BRA  South America   Brazil         brazil  2020-03-25
29       BRA  South America   Brazil         brazil  2020-03-26
30       BRA  South America   Brazil         brazil  2020-03-27
31       BRA  South America   Brazil         brazil  2020-03-28
32       BRA  South America   Brazil         brazil  2020-03-29
33       BRA  South America   Brazil         brazil  2020-03-30
34       BRA  South America   Brazil         brazil  2020-03-31
35       BRA  South America   Brazil         brazil  2020-04-01
36       BRA  South America   Brazil         brazil  2020-04-02
37       BRA  South America   Brazil         brazil  2020-04-03
38       BRA  South America   Brazil         brazil  2020-04-04
39       BRA  South America   Brazil         brazil  2020-04-05
40       BRA  South America   Brazil         brazil  2020-04-06
41       BRA  South America   Brazil         brazil  2020-04-07
42       BRA  South America   Brazil         brazil  2020-04-08
43       BRA  South America   Brazil         brazil  2020-04-09
44       BRA  South America   Brazil         brazil  2020-04-10
45       BRA  South America   Brazil         brazil  2020-04-11
46       BRA  South America   Brazil         brazil  2020-04-12
47       BRA  South America   Brazil         brazil  2020-04-13
48       BRA  South America   Brazil         brazil  2020-04-14
49       BRA  South America   Brazil         brazil  2020-04-15
50       BRA  South America   Brazil         brazil  2020-04-16
51       BRA  South America   Brazil         brazil  2020-04-17
52       BRA  South America   Brazil         brazil  2020-04-18
53       BRA  South America   Brazil         brazil  2020-04-19
54       BRA  South America   Brazil         brazil  2020-04-20
55       BRA  South America   Brazil         brazil  2020-04-21
56       BRA  South America   Brazil         brazil  2020-04-22
57       BRA  South America   Brazil         brazil  2020-04-23
58       BRA  South America   Brazil         brazil  2020-04-24
59       BRA  South America   Brazil         brazil  2020-04-25
60       BRA  South America   Brazil         brazil  2020-04-26
61       BRA  South America   Brazil

Podemos aplicar a maior parte dos métodos de strings que já vimos (`replace`,`starswith`,`strip`,`extract`, etc.) utilizando essa sintaxe. Uma outra operação interessante, para, por exemplo, separar em colunas distintas o primeiro e o último nome de uma pessoa é realizada através do método `split`. Vamos tentar fazer isso com a coluna do continente.

In [35]:
df_covid_br[['continent_1', 'continent_2']] = df_covid_br['continent'].str.split(pat=' ',n=1, expand=True, regex=False)

columns_to_show = ['iso_code','continent','continent_1','continent_2','location','lower_location','date']
df_covid_br[columns_to_show]

iso_code      continent continent_1 continent_2 location lower_location  \
0        BRA  South America       South     America   Brazil         brazil   
1        BRA  South America       South     America   Brazil         brazil   
2        BRA  South America       South     America   Brazil         brazil   
3        BRA  South America       South     America   Brazil         brazil   
4        BRA  South America       South     America   Brazil         brazil   
5        BRA  South America       South     America   Brazil         brazil   
6        BRA  South America       South     America   Brazil         brazil   
7        BRA  South America       South     America   Brazil         brazil   
8        BRA  South America       South     America   Brazil         brazil   
9        BRA  South America       South     America   Brazil         brazil   
10       BRA  South America       South     America   Brazil         brazil   
11       BRA  South America       South     America   Brazil         brazil   
12       BRA  South America       South     America   Brazil         brazil   
13       BRA  South America       South     America   Brazil         brazil   
14       BRA  South America       South     America   Brazil         brazil   
15       BRA  South America       South     America   Brazil         brazil   
16       BRA  South America       South     America   Brazil         brazil   
17       BRA  South America       South     America   Brazil         brazil   
18       BRA  South America       South     America   Brazil         brazil   
19       BRA  South America       South     America   Brazil         brazil   
20       BRA  South America       South     America   Brazil         brazil   
21       BRA  South America       South     America   Brazil         brazil   
22       BRA  South America       South     America   Brazil         brazil   
23       BRA  South America       South     America   Brazil         brazil   
24       BRA  South America       South     America   Brazil         brazil   
25       BRA  South America       South     America   Brazil         brazil   
26       BRA  South America       South     America   Brazil         brazil   
27       BRA  South America       South     America   Brazil         brazil   
28       BRA  South America       South     America   Brazil         brazil   
29       BRA  South America       South     America   Brazil         brazil   
30       BRA  South America       South     America   Brazil         brazil   
31       BRA  South America       South     America   Brazil         brazil   
32       BRA  South America       South     America   Brazil         brazil   
33       BRA  South America       South     America   Brazil         brazil   
34       BRA  South America       South     America   Brazil         brazil   
35       BRA  South America       South     America   Brazil         brazil   
36       BRA  South America       South     America   Brazil         brazil   
37       BRA  South America       South     America   Brazil         brazil   
38       BRA  South America       South     America   Brazil         brazil   
39       BRA  South America       South     America   Brazil         brazil   
40       BRA  South America       South     America   Brazil         brazil   
41       BRA  South America       South     America   Brazil         brazil   
42       BRA  South America       South     America   Brazil         brazil   
43       BRA  South America       South     America   Brazil         brazil   
44       BRA  South America       South     America   Brazil         brazil   
45       BRA  South America       South     America   Brazil         brazil   
46       BRA  South America       South     America   Brazil         brazil   
47       BRA  South America       South     America   Brazil         brazil   
48       BRA  South America       South     America   Brazil         brazil   
49       BRA  South America       South     America   

Vamos olhar com calma esse resultado e os argumentos que utilizamos dentro do método `split`.

* _pat_: determina os caracteres que serão utilizados para fazer a divisão do string.
* _n_: limita o número de divisões a serem feitas no string.
* _expand_: caso o valor desse argumento seja igual a `True`, a divisão do string irá gerar _n+1_ novas colunas no dataframe.
* _regex_: determina se o padrão _pat_, utilizado para a divisão do string, deve ser entendido como uma expressão regular ou não.

Bacana né? Esse método `split` nos permite fazer muita coisa legal com colunas de texto!

Por fim, uma outra funcionalidade interessante é a possibilidade de criação de novas colunas de strings utilizando dicionários. Podemos, por exemplo, utilizar essa funcionalidade para criar uma nova coluna que mostre se o número de novos casos por milhão está no quartil superior naquele dia ou não. 

In [36]:
df_covid_br['new_cases_per_million'].describe()

count     737.000000
mean      183.470531
std       173.332413
min         0.000000
25%        62.684000
50%       148.126000
75%       254.279000
max      1341.859000
Name: new_cases_per_million, dtype: float64

In [37]:
# criando coluna a partir de list comprehension
df_covid_br['quartil_superior_bool'] = [True if elem>=254.279 else False for elem in df_covid_br['new_cases_per_million']]


# criando coluna a partir de um dicionario
quartil_superior = {
    True:'Acima do 3º quartil de novos casos por milhão',
    False:'Abaixo'
}

df_covid_br['quartil_superior_cat'] = df_covid_br['quartil_superior_bool'].apply(lambda x: quartil_superior[x])

E qual é o resultado final?

In [38]:
df_covid_br[['date','new_cases_per_million','quartil_superior_bool','quartil_superior_cat']]

date  new_cases_per_million  quartil_superior_bool  \
0    2020-02-26                  0.005                  False   
1    2020-02-27                  0.000                  False   
2    2020-02-28                  0.000                  False   
3    2020-02-29                  0.005                  False   
4    2020-03-01                  0.000                  False   
5    2020-03-02                  0.000                  False   
6    2020-03-03                  0.000                  False   
7    2020-03-04                  0.009                  False   
8    2020-03-05                  0.000                  False   
9    2020-03-06                  0.042                  False   
10   2020-03-07                  0.000                  False   
11   2020-03-08                  0.033                  False   
12   2020-03-09                  0.023                  False   
13   2020-03-10                  0.028                  False   
14   2020-03-11                  0.033                  False   
15   2020-03-12                  0.065                  False   
16   2020-03-13                  0.463                  False   
17   2020-03-14                  0.000                  False   
18   2020-03-15                  0.051                  False   
19   2020-03-16                  0.178                  False   
20   2020-03-17                  0.565                  False   
21   2020-03-18                  0.238                  False   
22   2020-03-19                  1.164                  False   
23   2020-03-20                  0.804                  False   
24   2020-03-21                  1.065                  False   
25   2020-03-22                  2.453                  False   
26   2020-03-23                  1.766                  False   
27   2020-03-24                  1.509                  False   
28   2020-03-25                  1.435                  False   
29   2020-03-26                  2.014                  False   
30   2020-03-27                  2.019                  False   
31   2020-03-28                  2.276                  False   
32   2020-03-29                  1.645                  False   
33   2020-03-30                  1.509                  False   
34   2020-03-31                  5.318                  False   
35   2020-04-01                  5.229                  False   
36   2020-04-02                  5.645                  False   
37   2020-04-03                  4.729                  False   
38   2020-04-04                  6.094                  False   
39   2020-04-05                  3.598                  False   
40   2020-04-06                  4.818                  False   
41   2020-04-07                  8.753                  False   
42   2020-04-08                  9.982                  False   
43   2020-04-09                  8.982                  False   
44   2020-04-10                  7.225                  False   
45   2020-04-11                  5.089                  False   
46   2020-04-12                  6.846                  False   
47   2020-04-13                  5.785                  False   
48   2020-04-14                  8.561                  False   
49   2020-04-15                 14.290                  False   
50   2020-04-16                  9.837                  False   
51   2020-04-17                 15.220                  False   
52   2020-04-18                 13.907                  False   
53   2020-04-19                  9.327                  False   
54   2020-04-20                  9.762                  False   
55   2020-04-21                 10.916                  False   
56   2020-04-22                 12.514                  False   
57   2020-04-23                 19.996                  False   
58   2020-04-24                 18.725                  False   
59   2020-04-25                 24.678                  False   
60   2020-04-26                 17.645        

## Agrupamento e junção de DataFrames


Suponha que queiramos calcular médias mensais de novos casos e novos casos por milhão e salvar isso em um novo dataframe. Para essa operação podemos utilizar o famoso `groupby`. Vamos fazer isso para os dados brasileiros e norte-americanos de forma separada.

In [39]:
df_covid['ano_mes'] = df_covid['date'].str[0:7]
columns_to_keep = ['location','ano_mes','new_cases','new_cases_per_million']

df_covid_br = df_covid[df_covid['iso_code']=='BRA'][columns_to_keep]
df_covid_us = df_covid[df_covid['iso_code']=='USA'][columns_to_keep]

df_covid_br.head()

location  ano_mes  new_cases  new_cases_per_million
0   Brazil  2020-02        1.0                  0.005
1   Brazil  2020-02        0.0                  0.000
2   Brazil  2020-02        0.0                  0.000
3   Brazil  2020-02        1.0                  0.005
4   Brazil  2020-03        0.0                  0.000

In [40]:
df_covid_br_mensal = df_covid_br.groupby(by=['location','ano_mes'], as_index=False).mean()
df_covid_us_mensal = df_covid_us.groupby(by=['location','ano_mes'], as_index=False).mean()

df_covid_br_mensal

location  ano_mes      new_cases  new_cases_per_million
0    Brazil  2020-02       0.500000               0.002500
1    Brazil  2020-03     184.354839               0.861452
2    Brazil  2020-04    2715.666667              12.690400
3    Brazil  2020-05   13837.096774              64.661387
4    Brazil  2020-06   31597.517241             147.656517
5    Brazil  2020-07   40573.612903             189.602194
6    Brazil  2020-08   40141.225806             187.581516
7    Brazil  2020-09   30084.533333             140.586233
8    Brazil  2020-10   23238.645161             108.595065
9    Brazil  2020-11   26806.733333             125.268900
10   Brazil  2020-12   43195.709677             201.855258
11   Brazil  2021-01   49273.838710             230.258677
12   Brazil  2021-02   48198.928571             225.235607
13   Brazil  2021-03   71138.741935             332.434258
14   Brazil  2021-04   63723.733333             297.783600
15   Brazil  2021-05   60734.967742             283.817000
16   Brazil  2021-06   67080.266667             313.468767
17   Brazil  2021-07   43608.064516             203.782323
18   Brazil  2021-08   27840.322581             130.098935
19   Brazil  2021-09   18009.931034              84.161034
20   Brazil  2021-10   12331.064516              57.623548
21   Brazil  2021-11    9517.266667              44.474533
22   Brazil  2021-12    6183.741935              28.896806
23   Brazil  2022-01  102312.612903             478.111000
24   Brazil  2022-02  119037.178571             556.265607
25   Brazil  2022-03   48845.800000             228.258600

Note que fizemos um dataframe para o Brasil e outro para os Estados Unidos. Podíamos ter feito tudo junto? Podíamos. Mas fizemos dessa forma justamente para mostrar outra funcionalidade bastante importante quando trabalhamos com bases de dados: a junção de duas bases diferentes. Essa junção de bases distintas pode ser realizada utilizando duas funções distintas: `concat` e `merge`. 

A função `concat` "soma" duas bases, criando uma nova base que apenas junta as linhas dos diferentes dataframes. Isso é muito útil, por exemplo, quando geramos dataframes dentro de um loop e queremos ir juntando cada novo dataframe a um grande e único.

In [41]:
df_covid_concat = pd.concat(objs=[df_covid_br_mensal, df_covid_us_mensal]).reset_index(drop=True)

df_covid_concat

location  ano_mes      new_cases  new_cases_per_million
0          Brazil  2020-02       0.500000               0.002500
1          Brazil  2020-03     184.354839               0.861452
2          Brazil  2020-04    2715.666667              12.690400
3          Brazil  2020-05   13837.096774              64.661387
4          Brazil  2020-06   31597.517241             147.656517
5          Brazil  2020-07   40573.612903             189.602194
6          Brazil  2020-08   40141.225806             187.581516
7          Brazil  2020-09   30084.533333             140.586233
8          Brazil  2020-10   23238.645161             108.595065
9          Brazil  2020-11   26806.733333             125.268900
10         Brazil  2020-12   43195.709677             201.855258
11         Brazil  2021-01   49273.838710             230.258677
12         Brazil  2021-02   48198.928571             225.235607
13         Brazil  2021-03   71138.741935             332.434258
14         Brazil  2021-04   63723.733333             297.783600
15         Brazil  2021-05   60734.967742             283.817000
16         Brazil  2021-06   67080.266667             313.468767
17         Brazil  2021-07   43608.064516             203.782323
18         Brazil  2021-08   27840.322581             130.098935
19         Brazil  2021-09   18009.931034              84.161034
20         Brazil  2021-10   12331.064516              57.623548
21         Brazil  2021-11    9517.266667              44.474533
22         Brazil  2021-12    6183.741935              28.896806
23         Brazil  2022-01  102312.612903             478.111000
24         Brazil  2022-02  119037.178571             556.265607
25         Brazil  2022-03   48845.800000             228.258600
26  United States  2020-01       0.777778               0.002333
27  United States  2020-02       0.586207               0.001759
28  United States  2020-03    6195.290323              18.609226
29  United States  2020-04   29444.100000              88.443333
30  United States  2020-05   22969.967742              68.996452
31  United States  2020-06   28578.766667              85.844033
32  United States  2020-07   61294.612903             184.114871
33  United States  2020-08   48365.322581             145.278355
34  United States  2020-09   39903.133333             119.859833
35  United States  2020-10   61870.806452             185.845677
36  United States  2020-11  149008.733333             447.587733
37  United States  2020-12  211725.580645             635.974742
38  United States  2021-01  198457.129032             596.119355
39  United States  2021-02   86034.107143             258.426643
40  United States  2021-03   58529.064516             175.807742
41  United States  2021-04   62970.333333             189.148333
42  United States  2021-05   29748.451613              89.357484
43  United States  2021-06   13276.700000              39.880100
44  United States  2021-07   42530.483871             127.751742
45  United States  2021-08  138009.000000             414.547258
46  United States  2021-09  138317.100000             415.472700
47  United States  2021-10   80986.354839             243.264323
48  United States  2021-11   84910.433333             255.051300
49  United States  2021-12  200890.870968             603.429839
50  United States  2022-01  650778.903226            1954.789548
51  United States  2022-02  145005.857143             435.564107
52  United States  2022-03   44279.200000             133.004200

Já a função `merge` une duas bases de acordo com colunas identificadoras. Vamos juntar as bases do Brasil e EUA utilizando a coluna de ano-mês como identificadora.

In [42]:
df_covid_merge = pd.merge(df_covid_br_mensal, df_covid_us_mensal, how='inner', on=['ano_mes'])

df_covid_merge

location_x  ano_mes    new_cases_x  new_cases_per_million_x     location_y  \
0      Brazil  2020-02       0.500000                 0.002500  United States   
1      Brazil  2020-03     184.354839                 0.861452  United States   
2      Brazil  2020-04    2715.666667                12.690400  United States   
3      Brazil  2020-05   13837.096774                64.661387  United States   
4      Brazil  2020-06   31597.517241               147.656517  United States   
5      Brazil  2020-07   40573.612903               189.602194  United States   
6      Brazil  2020-08   40141.225806               187.581516  United States   
7      Brazil  2020-09   30084.533333               140.586233  United States   
8      Brazil  2020-10   23238.645161               108.595065  United States   
9      Brazil  2020-11   26806.733333               125.268900  United States   
10     Brazil  2020-12   43195.709677               201.855258  United States   
11     Brazil  2021-01   49273.838710               230.258677  United States   
12     Brazil  2021-02   48198.928571               225.235607  United States   
13     Brazil  2021-03   71138.741935               332.434258  United States   
14     Brazil  2021-04   63723.733333               297.783600  United States   
15     Brazil  2021-05   60734.967742               283.817000  United States   
16     Brazil  2021-06   67080.266667               313.468767  United States   
17     Brazil  2021-07   43608.064516               203.782323  United States   
18     Brazil  2021-08   27840.322581               130.098935  United States   
19     Brazil  2021-09   18009.931034                84.161034  United States   
20     Brazil  2021-10   12331.064516                57.623548  United States   
21     Brazil  2021-11    9517.266667                44.474533  United States   
22     Brazil  2021-12    6183.741935                28.896806  United States   
23     Brazil  2022-01  102312.612903               478.111000  United States   
24     Brazil  2022-02  119037.178571               556.265607  United States   
25     Brazil  2022-03   48845.800000               228.258600  United States   

      new_cases_y  new_cases_per_million_y  
0        0.586207                 0.001759  
1     6195.290323                18.609226  
2    29444.100000                88.443333  
3    22969.967742                68.996452  
4    28578.766667                85.844033  
5    61294.612903               184.114871  
6    48365.322581               145.278355  
7    39903.133333               119.859833  
8    61870.806452               185.845677  
9   149008.733333               447.587733  
10  211725.580645               635.974742  
11  198457.129032               596.119355  
12   86034.107143               258.426643  
13   58529.064516               175.807742  
14   62970.333333               189.148333  
15   29748.451613                89.357484  
16   13276.700000                39.880100  
17   42530.483871               127.751742  
18  138009.000000               414.547258  
19  138317.100000               415.472700  
20   80986.354839               243.264323  
21   84910.433333               255.051300  
22  200890.870968               603.429839  
23  650778.903226              1954.789548  
24  145005.857143               435.564107  
25   44279.200000               133.004200

Que legal! Tome um tempo em casa para entender as particularidades dessa função `merge`, elas são muitas.

Mas note que existiam colunas com o mesmo nome nas bases. Por padrão o pandas renomeia essas colunas com `_x` e `_y`. Vamos renomear essas colunas utilizando dicionários, uma forma alternativa ao que fizemos anteriormente.

In [43]:
df_covid_merge.drop(columns=['location_x','location_y'], inplace=True)

dict_rename = {
    'new_cases_x':'nc_br',
    'new_cases_per_million_x':'ncpm_br',
    'new_cases_y':'nc_us',
    'new_cases_per_million_y':'ncpm_us'
}

df_covid_merge.rename(columns=dict_rename, inplace=True)

df_covid_merge

ano_mes          nc_br     ncpm_br          nc_us      ncpm_us
0   2020-02       0.500000    0.002500       0.586207     0.001759
1   2020-03     184.354839    0.861452    6195.290323    18.609226
2   2020-04    2715.666667   12.690400   29444.100000    88.443333
3   2020-05   13837.096774   64.661387   22969.967742    68.996452
4   2020-06   31597.517241  147.656517   28578.766667    85.844033
5   2020-07   40573.612903  189.602194   61294.612903   184.114871
6   2020-08   40141.225806  187.581516   48365.322581   145.278355
7   2020-09   30084.533333  140.586233   39903.133333   119.859833
8   2020-10   23238.645161  108.595065   61870.806452   185.845677
9   2020-11   26806.733333  125.268900  149008.733333   447.587733
10  2020-12   43195.709677  201.855258  211725.580645   635.974742
11  2021-01   49273.838710  230.258677  198457.129032   596.119355
12  2021-02   48198.928571  225.235607   86034.107143   258.426643
13  2021-03   71138.741935  332.434258   58529.064516   175.807742
14  2021-04   63723.733333  297.783600   62970.333333   189.148333
15  2021-05   60734.967742  283.817000   29748.451613    89.357484
16  2021-06   67080.266667  313.468767   13276.700000    39.880100
17  2021-07   43608.064516  203.782323   42530.483871   127.751742
18  2021-08   27840.322581  130.098935  138009.000000   414.547258
19  2021-09   18009.931034   84.161034  138317.100000   415.472700
20  2021-10   12331.064516   57.623548   80986.354839   243.264323
21  2021-11    9517.266667   44.474533   84910.433333   255.051300
22  2021-12    6183.741935   28.896806  200890.870968   603.429839
23  2022-01  102312.612903  478.111000  650778.903226  1954.789548
24  2022-02  119037.178571  556.265607  145005.857143   435.564107
25  2022-03   48845.800000  228.258600   44279.200000   133.004200

## Eficiência e _dtypes_


DataFrames podem ser objetos bastante pesados, com milhões de linhas e milhares de colunas. Isso por vezes pode ser um problemão para nós. Existem bibliotecas que servem ao propósito de trabalhar de forma mais eficiente com bases de dados muito grandes (e.g., [`Dask`](https://www.dask.org/)), mas algumas funções dentro do próprio Pandas já conseguem nos ajudar bastante em grande parte das situações.

Vamos começar relendo a base completa de dados da covid com os 10 países com o maior número de casos. Além disso, imagine que por um descuido nosso tenhamos replicado todas as entradas por 10 vezes seguidas. Qual é o tamanho dessa base e quantos bytes de memória foram alocados para esse objeto?

In [44]:
df_covid_duplicada = pd.DataFrame()

for i in range(0,10):
    df_covid_duplicada = pd.concat([df_covid_duplicada, df_covid]).reset_index(drop=True)

df_covid_duplicada.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76630 entries, 0 to 76629
Data columns (total 68 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   iso_code                                    76630 non-null  object 
 1   continent                                   76630 non-null  object 
 2   location                                    76630 non-null  object 
 3   date                                        76630 non-null  object 
 4   total_cases                                 76630 non-null  float64
 5   new_cases                                   76410 non-null  float64
 6   new_cases_smoothed                          74840 non-null  float64
 7   total_deaths                                73450 non-null  float64
 8   new_deaths                                  73270 non-null  float64
 9   new_deaths_smoothed                         71730 non-null  float64
 10  total_case

O DataFrame `df_covid_duplicada` possui $76,630$ linhas, 67 colunas e está usando 64.6 MB da nossa memória RAM. O primeiro passo para tornar o objeto mais eficiente é ver se encontramos linhas duplicadas em todas suas colunas, que não nos trazem nenhuma nova informação mas carregam desnecessariamente nossos pentes de memória. Para esse fim utilizaremos a função `drop_duplicates`.

In [45]:
df_covid_duplicada.drop_duplicates(inplace=True)

df_covid_duplicada.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7663 entries, 0 to 7662
Data columns (total 68 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   iso_code                                    7663 non-null   object 
 1   continent                                   7663 non-null   object 
 2   location                                    7663 non-null   object 
 3   date                                        7663 non-null   object 
 4   total_cases                                 7663 non-null   float64
 5   new_cases                                   7641 non-null   float64
 6   new_cases_smoothed                          7484 non-null   float64
 7   total_deaths                                7345 non-null   float64
 8   new_deaths                                  7327 non-null   float64
 9   new_deaths_smoothed                         7173 non-null   float64
 10  total_cases_

Legal, conseguimos dropar as linhas duplicadas e reduzimos o comprometimento de memória de 64.6 MB para 6.5MB.

No entanto, os tipos de dados de cada coluna não nos parecem os mais adequados. Uma coluna do tipo `float64` consume 4x mais memória do que uma coluna do tipo `float16` e 8x mais memória do que uma coluna do tipo `int8`, por exemplo. Da mesma forma, uma coluna do tipo `object` consome muito mais memória do que uma coluna que o Pandas entende como do tipo categórica em grande parte dos casos. Mas o que são esses tipos todos?

* **int8 / uint8**: consome 1 byte (8-bit) de memória, o valor numérico deve ser inteiro e estar no intervalo $[-128 , 127]$ / $[0 , 255]$
* **int16 / uint16**: consome 2 bytes de memória, o valor numérico deve ser inteiro e estar no intervalo $[-32768 , 32768]$ / $[0,65535]$
* **int32 / uint32**: consome 4 bytes de memória e aceita valores numéricos inteiros com até 10 dígitos, da ordem de 2 bilhões.
* **int64 / uint64**: consome 8 bytes de memória e aceita valores numéricos inteiros ainda maiores.
* **float16 / float32 / float64**: consome 2, 4 e 8 bytes de memória, respectivamente, e aceita valores com casas decimais delimitado pelos mesmos intervalos dos tipos anteriores.
* **bool**: consome 1 byte de memória e aceita apenas dois valores `True` e `False`.
* **object**: o quanto consome de memória pode variar, mas, por aceitar valores numéricos e strings de todo tipo, consome ao menos 8 bytes de memória.
* **category**: o quanto consome de memória pode variar e depende da relação entre o número de valores únicos na coluna e o número de linhas de dados.

Beleza, devemos fugir do tipo `object` e tentar reduzir as colunas numéricas para tipos menos demandantes em termos de memória. Como fazer isso? A função `astype` é nossa companheira nesse caso.

Voltando ao nosso dataframe original, as colunas `iso_code`, `continent` e `location` podem ser transformadas em colunas do tipo categórica sem nenhuma perda de informação. Comecemos por elas.

In [46]:
columns_to_cat = ['iso_code','continent','location']

for c in columns_to_cat:
    df_covid_duplicada[c] = df_covid_duplicada[c].astype('category')

O quanto isso nos ajudou?

In [47]:
df_covid_duplicada.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7663 entries, 0 to 7662
Data columns (total 68 columns):
 #   Column                                      Non-Null Count  Dtype   
---  ------                                      --------------  -----   
 0   iso_code                                    7663 non-null   category
 1   continent                                   7663 non-null   category
 2   location                                    7663 non-null   category
 3   date                                        7663 non-null   object  
 4   total_cases                                 7663 non-null   float64 
 5   new_cases                                   7641 non-null   float64 
 6   new_cases_smoothed                          7484 non-null   float64 
 7   total_deaths                                7345 non-null   float64 
 8   new_deaths                                  7327 non-null   float64 
 9   new_deaths_smoothed                         7173 non-null   float64 
 10  

Caramba! Esse pequena alteração reduziu o comprometimento de memória em aproximadamente $20\%$.

Vamos tentar transformar as colunas de `total_cases`, `new_cases`, `total_deaths` e `new_deaths` em colunas do tipo `int32` ao invés de `float64` já que são colunas sabidamente de números inteiros. Não esqueça de lidar com os valores missing antes, já que dados do tipo `int` não aceitam `NaN` ou `infty` como valores.

In [48]:
columns_to_int = ['total_cases','new_cases','total_deaths','new_deaths']

for c in columns_to_int:
    df_covid_duplicada[c] = df_covid_duplicada[c].fillna(-1)
    df_covid_duplicada[c] = df_covid_duplicada[c].astype('int32')

O quanto isso nos ajudou?

In [49]:
df_covid_duplicada.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7663 entries, 0 to 7662
Data columns (total 68 columns):
 #   Column                                      Non-Null Count  Dtype   
---  ------                                      --------------  -----   
 0   iso_code                                    7663 non-null   category
 1   continent                                   7663 non-null   category
 2   location                                    7663 non-null   category
 3   date                                        7663 non-null   object  
 4   total_cases                                 7663 non-null   int32   
 5   new_cases                                   7663 non-null   int32   
 6   new_cases_smoothed                          7484 non-null   float64 
 7   total_deaths                                7663 non-null   int32   
 8   new_deaths                                  7663 non-null   int32   
 9   new_deaths_smoothed                         7173 non-null   float64 
 10  

Reduzimos mais um pouco o comprometimento de memória, embora a diferença não tenha sido tão grande. Em dataframes com milhões de linhas e milhares de colunas, no entanto, essa redução pode fazer toda a diferença. Dica: dê uma olhada na função `pandas.to_numeric` e no argumento `downcast` caso você não saiba para qual tipo de dado numérico deve ir.

No fim das contas, parte importante da estratégia de otimização na gestão de memória de dataframes vem de conhecermos os tipos mais adequados de dados para cada coluna **antes** da leitura do dataframe. Isso pode ser feito lendo primeiro um amostra de poucas linhas (e.g., 10 ou 20) do dataframe com o qual iremos trabalhar para entender a base de dados e só a partir daí ler o dataframe completo com a função `read_csv` (ou similar) e passar uma lista de tipo de dados ao argumento `dtype` (exemplo do algoritmo [aqui](https://vincentteyssier.medium.com/optimizing-the-size-of-a-pandas-dataframe-for-low-memory-environment-5f07db3d72e)). Tente isso em casa! **E não se esqueça: fuja de dados do tipo `object`!**

# Exportando o DataFrame

Por fim, a última coisa que gostaríamos de aprender nesse aulão de Pandas é como salvar o dataframe, resultado de todas as nossas operações, para um novo `csv` ou arquivo de qualquer outro tipo. Assim como tínhamos funções do tipo `read_csv` para trazer arquivos de fora, temos métodos do tipo `to_csv` para salvar um dado dataframe em um novo arquivo a ser utilizado em outros softwares.

A sintaxe é bastante simples:

In [50]:
df_covid_duplicada.to_csv('df_resultado_aula_pandas.csv', sep=',', encoding='utf8', index=False)

os.listdir()

['df_resultado_aula_pandas.csv',
 'EAE1106 - Aula01.html',
 'EAE1106 - Aula01.ipynb',
 'EAE1106 - Aula02.html',
 'EAE1106 - Aula02.ipynb',
 'EAE1106 - Aula03 e Aula04.html',
 'EAE1106 - Aula03 e Aula04.ipynb',
 'EAE1106 - Aula05.html',
 'EAE1106 - Aula05.ipynb',
 'EAE1106 - Aula06 e Aula07.html',
 'EAE1106 - Aula06 e Aula07.ipynb',
 'EAE1106 - Aula08.html',
 'EAE1106 - Aula08.ipynb',
 'EAE1106 - Aula09.html',
 'EAE1106 - Aula09.ipynb',
 'EAE1106 - Aula10.html',
 'EAE1106 - Exercícios.ipynb',
 'owid-covid-data_top10.csv']

Olha o arquivo que geramos aí, minha gente! 

Tente exportar o dataframe em outros formatos e importá-lo em outros softwares. Lembre-se, assim como quando queremos aprender novas línguas como inglês, alemão ou mandarim, em programação a fluência chega apenas com muito treino, tentativa e erro.